In [1]:
import numpy as np
from pathlib import Path

In [6]:
run_folder = "run_HcX_globTag/"

nfs_path = "/nfs/dust/belle2/user/axelheim/BranchSeparator/" + run_folder


#data_folder = "50k_realTree_clean"
#data_folder =  "50k_realTree_charge" 
#data_folder =  "50k_realTree_IDs" 
#data_folder =  "50k_realTree_IDs_charge" 
data_folder =  "TSD_15k_each_6trees_IDs_charge"
top_dir = Path(nfs_path)
dataset_dir = Path(nfs_path + 'data/' + data_folder)


leaves = np.load(dataset_dir / 'leaves.npy')    
is_left = np.load(dataset_dir / 'is_left_arr.npy')
glob_tag = np.load(dataset_dir / 'global_tag.npy')

In [7]:
print(leaves.shape)
print(is_left.shape)
print(glob_tag.shape)


(90000, 11, 7)
(90000, 11)
(90000, 12)


In [8]:
np.set_printoptions(precision=2)
np.set_printoptions(suppress=True)

i = 2
print(f"leaves: \n {leaves[i]}")
print(f"is_left array: \n {is_left[i]}")
print(f"glob_tag array: \n {glob_tag[i]}")


leaves: 
 [[-1336.8    130.33  2574.6   2945.61    -1.       0.15     0.96]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [   23.75  -337.97  -253.02   650.26    -1.       0.12     0.9 ]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [ 1246.82  -177.73  -430.38  1338.27     1.       0.94     0.  ]
 [   30.06     1.53   -45.04    54.18     0.       0.06     0.02]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [  384.29   483.02  -208.78   666.46     1.       0.82     0.09]]
is_left array: 
 [ 0. -1. -1.  1. -1. -1. -1.  1.  2. -1.  1.]
glob_tag array: 
 [b'K-_1' b'-1' b'-1' b'K-_2' b'-1' b'-1' b'-1' b'pi+_2' b'BG_gamma' b'-1'
 b'pi+_1' b'1']


In [8]:
### Mass Test ###