In [2]:
import numpy as np
from pathlib import Path

In [4]:
run_folder = "run_BsXHc/"

nfs_path = "/nfs/dust/belle2/user/axelheim/BranchSeparator/" + run_folder



data_folder =  "TSD_BsXHc_15k_each_6trees_IDs_charge"
top_dir = Path(nfs_path)
dataset_dir = Path(nfs_path + 'data/' + data_folder)


leaves = np.load(dataset_dir / 'leaves.npy')    
is_left = np.load(dataset_dir / 'is_left_arr.npy')
glob_tag = np.load(dataset_dir / 'global_tag.npy')

In [5]:
print(leaves.shape)
print(is_left.shape)
print(glob_tag.shape)


(90000, 15, 7)
(90000, 15)
(90000, 16)


In [6]:
np.set_printoptions(precision=2)
np.set_printoptions(suppress=True)

i = 2
print(f"leaves: \n {leaves[i]}")
print(f"is_left array: \n {is_left[i]}")
print(f"glob_tag array: \n {glob_tag[i]}")

leaves: 
 [[ -913.48  1583.06  1929.66  2661.53    -1.       0.95     0.1 ]
 [  994.42   517.02  -397.9   1287.85     1.       0.01     0.96]
 [  -23.09   309.22   629.12   715.22    -1.       0.96     0.07]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [-1159.48   204.24  1681.41  2057.39     1.       0.97     0.12]
 [  -35.02   169.41  -235.32   323.88    -1.       0.97     0.01]
 [  -57.82  -160.03    -7.96   170.34     0.       0.02     0.16]
 [  270.22 -1187.09   133.97  1232.78     1.       0.85     0.  ]
 [ -276.05  -710.95  -789.05  1203.44    -1.       0.01     0.95]
 [  432.37    12.52  -321.14   556.62    -1.       1.       0.03]
 [ -427.85     5.6    464.63   801.87     1.       0.       0.86]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [ 1229.51  -704.87    62.73  1425.5      1.       1.       0.02]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]]

In [8]:
print_arr = [0,0,0,0,0,0]
i = 0
while sum(print_arr) < 6:
    mode = int(str(glob_tag[i,-1])[2])
    
    if print_arr[mode] == 0:
        print_arr[mode] = 1
        
        print(mode,mode,mode,mode,mode,mode,mode,mode,mode,mode,mode,mode)
        print(f"leaves: \n {leaves[i]}")
        print(f"is_left array: \n {is_left[i]}")
        print(f"glob_tag array: \n {glob_tag[i]}")
        print("\n\n\n\n")
        
    i += 1
        


1 1 1 1 1 1 1 1 1 1 1 1
leaves: 
 [[  -1.     -1.     -1.     -1.     -1.     -1.     -1.  ]
 [-216.31  -79.66    2.21  230.53    0.      0.18    0.  ]
 [  -1.     -1.     -1.     -1.     -1.     -1.     -1.  ]
 [-988.95 -350.35  302.97 1092.04    0.      0.02    0.04]
 [-446.59  652.62  638.18 1129.9    -1.      0.08    0.95]
 [ 310.69 -502.64 -244.19  654.52   -1.      0.99    0.04]
 [-347.45  435.53  139.52  757.57   -1.      0.      0.98]
 [1424.21 -334.11  415.65 1527.21    1.      0.99    0.01]
 [ 612.39  213.01  -85.92  654.05    0.      0.01    0.12]
 [-103.1   178.6    21.63  250.19   -1.      0.97    0.05]
 [-248.74   -7.43  622.    684.41   -1.      1.      0.05]
 [-141.92  -25.71  256.35  325.76    1.      1.      0.12]
 [-539.97  239.81  444.42  889.17    1.      0.05    1.  ]
 [  -1.     -1.     -1.     -1.     -1.     -1.     -1.  ]
 [ 247.84   87.39   50.03  267.52    0.      0.03    0.13]]
is_left array: 
 [-1.  1. -1.  1.  3.  2.  2.  1.  1.  1.  1.  3.  1. -1.  1.]
g

In [7]:
print_arr = [0,0,0,0,0,0]

sum(print_arr)

0

1