In [2]:
import numpy as np
from pathlib import Path

In [17]:
run_folder = "run_BsX/"

nfs_path = "/nfs/dust/belle2/user/axelheim/BranchSeparator/" + run_folder



data_folder =  "TSD_BsX_15k_each_6trees_IDs_charge"
top_dir = Path(nfs_path)
dataset_dir = Path(nfs_path + 'data/' + data_folder)


leaves = np.load(dataset_dir / 'leaves.npy')    
is_left = np.load(dataset_dir / 'is_left_arr.npy')
glob_tag = np.load(dataset_dir / 'global_tag.npy')

In [18]:
print(leaves.shape)
print(is_left.shape)
print(glob_tag.shape)


(90000, 12, 7)
(90000, 12)
(90000, 13)


In [19]:
np.set_printoptions(precision=2)
np.set_printoptions(suppress=True)

i = 2
print(f"leaves: \n {leaves[i]}")
print(f"is_left array: \n {is_left[i]}")
print(f"glob_tag array: \n {glob_tag[i]}")

leaves: 
 [[  -56.27  -115.16   -97.77   161.2      0.       0.       0.05]
 [  426.43    62.01  1167.79  1252.61     1.       0.93     0.12]
 [  854.01  -567.81  1383.97  1722.53     0.       0.04     0.11]
 [ -516.16   206.47  -852.37  1027.22    -1.       0.98     0.05]
 [  -20.92  -542.17  -330.37   804.71     1.       0.08     1.  ]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [  -15.16  -115.44    44.14   124.52     0.       0.       0.03]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [   47.45   -15.53    19.1     53.45     0.       0.14     0.  ]
 [  -21.01   551.57   325.62   655.97    -1.       0.99     0.05]
 [ 1373.51 -1337.71  -429.09  2025.87    -1.       0.01     0.98]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]]
is_left array: 
 [ 1.  1.  1.  1.  2. -1.  1. -1.  2.  2.  0. -1.]
glob_tag array: 
 [b'gamma_s3' b'pi+_s1' b'gamma_s1' b'pi-_s2' b'BG_K+'
 b'pi-_s1_DELETED_theta' b'gamma_s4' b'K+_s1_DELETED_rand'

In [20]:
print_arr = [0,0,0,0,0,0]
i = 0
while sum(print_arr) < 6:
    mode = int(str(glob_tag[i,-1])[2])
    
    if print_arr[mode] == 0:
        print_arr[mode] = 1
        
        print(mode,mode,mode,mode,mode,mode,mode,mode,mode,mode,mode,mode)
        print(f"leaves: \n {leaves[i]}")
        print(f"is_left array: \n {is_left[i]}")
        print(f"glob_tag array: \n {glob_tag[i]}")
        print("\n\n\n\n")
        
    i += 1
        


4 4 4 4 4 4 4 4 4 4 4 4
leaves: 
 [[   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [  259.81    21.67   215.2    365.9     -1.       0.95     0.01]
 [ 1306.01  1326.01   912.92  2077.74     1.       0.97     0.04]
 [ -634.92   -91.54  -145.95   657.88     0.       0.02     0.06]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [ -991.5   -406.62  -205.34  1197.76     1.       0.07     0.97]
 [   -1.      -1.      -1.      -1.      -1.      -1.      -1.  ]
 [   82.35 -1018.44   981.61  1423.78    -1.       0.94     0.1 ]
 [ -483.15   268.09  -238.02   778.46    -1.       0.02     0.88]
 [  -33.86    15.91   -39.57    54.46     0.       0.02     0.01]
 [ 1255.37  -940.05   599.57  1684.86    -1.       0.91     0.07]]
is_left array: 
 [-1.  2.  1.  1. -1. -1.  1. -1.  1.  2.  1.  0.]
glob_tag array: 
 [b'-1' b'BG_pi-' b'pi+_s1' b'gamma_s1' b'-1' b'-1' b'K+_s1'
 b'pi-_1_DELETED_theta' b'pi

In [7]:
print_arr = [0,0,0,0,0,0]

sum(print_arr)

0

1