In [3]:
import numpy as np
import torch

In [78]:
y = torch.tensor([[[1, 2, 0, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0,-1,-1,-1],
                 [1, 2, 0, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0,-1,-1,-1],
                 [1, 2, 0, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0,-1,-1,-1],
                 [1, 2, 0, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0,-1,-1,-1],
                 [1, 2, 0, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0,-1,-1,-1],
                 [2,2,2, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0,-1,-1,-1],
                 [1, 2, 0, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0,-1,-1,-1],
                 [1, 2, 0, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0,-1,-1,-1]]])

y_pred = torch.tensor([[[0,0,0, 2,2,2,1, 2, 0,1, 2, 0,0,0,0,1,1,1],
                      [0,0,0, 2,2,2,1, 2, 0,1, 2, 0,0,0,0,1,1,1],
                      [0,0,0, 2,2,2,1, 2, 0,1, 2, 0,0,0,0,1,1,1],
                      [0,0,0, 2,2,2,1, 2, 0,1, 2, 0,0,0,0,1,1,1],
                      [0,0,0, 2,2,2,1, 2, 0,1, 2, 0,0,0,0,1,1,1],
                      [2,2,2, 2,2,2,1, 2, 0,1, 2, 0,0,0,0,1,1,1],
                      [0,0,0, 2,2,2,1, 2, 0,1, 2, 0,0,0,0,1,1,1],
                      [0,0,0, 2,2,2,1, 2, 0,1, 2, 0,0,0,0,1,1,1]]])

In [79]:
print(y_pred.shape)
print(y.shape)

torch.Size([1, 8, 18])
torch.Size([1, 8, 18])


In [80]:
ignored_class = -1
custom_class = 2

indices = y_pred #torch.argmax(y_pred, dim=1)

mask = (y != ignored_class)
mask &= (indices != ignored_class)
y = y[mask]
indices = indices[mask]

mask2 = (y == custom_class)
y = y[mask2]
indices = indices[mask2]
#indices[indices != custom_class] = -10

print(y.shape)
print(indices.shape)
print(y)
print(indices)
print(mask2)
correct = torch.eq(indices, y).view(-1)

print(torch.sum(correct).item())
print(correct.shape[0])

torch.Size([34])
torch.Size([34])
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
tensor([0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 0, 2, 2, 2, 0, 2, 2, 2])
tensor([False,  True, False, False,  True, False, False,  True, False, False,
         True, False, False, False, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False, False, False,
        False,  True, False, False,  True, False, False,  True, False, False,
         True, False, False, False, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False, False, False,
        False,  True, False, False,  True, False, False,  True, False, False,
         True, False, False, False, False,  True,  True,  True, False,  True,
        False, False,  True, False, False,  True, False, False, False, False,
        False,  True, Fals

In [82]:
x = None
if x == None:
    print("hi")

hi


In [49]:
output_y_pred, counts_y_pred = torch.unique(y_pred, return_counts=True)
print(output_y_pred)
print(counts_y_pred)


output_y, counts_y = torch.unique(y, return_counts=True)
print(output_y)
print(counts_y)

print("")
print("xxx 0:", counts_y_pred[0].item()/counts_y[1].item())
print(counts_y_pred[0].item(),counts_y[1].item())

tensor([0, 1, 2])
tensor([61, 40, 43])
tensor([-1,  0,  1,  2])
tensor([24, 55, 31, 34])

xxx 0: 1.1090909090909091
61 55


In [67]:
x1 = torch.tensor([[[1, 2, 0, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0],
                 [1, 2, 0, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0],
                 [1, 2, 0, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0],
                 [1, 2, 0, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0],
                 [1, 2, 0, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0],
                 [2,2,2, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0],
                 [1, 2, 0, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0],
                 [1, 2, 0, 1, 2, 0,1, 2, 0,1, 2, 0,0,0,0]]])

x2 = torch.tensor([[[0,0,0, 2,2,2,1, 2, 0,1, 2, 0,0,0,0],
                      [0,0,0, 2,2,2,1, 2, 0,1, 2, 0,0,0,0],
                      [0,0,0, 2,2,2,1, 2, 0,1, 2, 0,0,0,0],
                      [0,0,0, 2,2,2,1, 2, 0,1, 2, 0,0,0,0],
                      [0,0,0, 2,2,2,1, 2, 0,1, 2, 0,0,0,0],
                      [2,2,2, 2,2,2,1, 2, 0,1, 2, 0,0,0,0],
                      [0,0,0, 2,2,2,1, 2, 0,1, 2, 0,0,0,0],
                      [0,0,0, 2,2,2,1, 2, 0,1, 2, 0,0,0,0]]])
print(x1.shape)
print(x2.shape)

torch.sum(torch.eq(x1, x2))

torch.Size([1, 8, 15])
torch.Size([1, 8, 15])


tensor(90)